### PR TITLE
support costFromWeight envelopeType

### PR DESCRIPTION
**Pull request by jordipainan**

### CODE REVIEW

**Review by brickpop — COMMENTED** [review]
So far changes look good. However, we should also add this flag to the tests

**Comment by jordipainan** [comment]
>     * [ ]  I think we should add this flag to the TS tests as well
> 
>     * [ ]  If we want to restrict this flag to EVM processes only, then the contract is missing such check.
>       
>       * Do we really need to enforce this within the contract?
>       * Can't we need this flag on non-EVM processes, in the future?

Adding the test.
After internal discussion we do not want to restrict the flag to EVM processes

**Comment by jordipainan** [comment]
Added more tests on test/wrappers/envelope-type :) @brickpop

**Comment by brickpop** [comment]
@jordipainan Looks good to me :+1:

**Pull request merged**
